src/main/java/com/daniloaraujosilva/jogodobicho/controller/mb/JogoDoBichoMB.java
package com.daniloaraujosilva.jogodobicho.controller.mb;

import java.io.Serializable;
import java.util.HashMap;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.apache.log4j.Logger;

import com.daniloaraujosilva.jogodobicho.model.bo.JogoDoBichoBO;
import com.daniloaraujosilva.jogodobicho.model.helper.FacesMessager;
import com.daniloaraujosilva.jogodobicho.model.pojo.NodePojo;

/**
 * 
 */
@ViewScoped
@ManagedBean(name="jogoDoBichoMB")
public class JogoDoBichoMB implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3298340293849150158L;
	
	/**
	 * 
	 */
	private Logger logger = Logger.getLogger(getClass());
	
	/**
	 * Objeto de negócios. Utilizado normalmente com DAOs e entidades.
	 * As regras de negócio do jogo são delegadas a essa classe.
	 */
	private JogoDoBichoBO bo;
	
	/**
	 * Permissões, neste caso da tela.
	 * Indica o que será ou não renderizado.
	 */
	private HashMap<String, Boolean> permissions;

	/**
	 * 
	 */
	public JogoDoBichoMB() {
		super();
	}
	
	/**
	 * 
	 */
	@PostConstruct
	public void init() {
		try {
			permissions = new HashMap<String, Boolean>();
			permissions.put("escolhendoAnimal", true);
			
			bo = new JogoDoBichoBO();
			bo.start();
		} catch (Exception exception) {
			manageThrowable(exception);
		}
	}

	/**
	 * 
	 * @return
	 */
	public NodePojo getCurrent() {
		return bo.getCurrent();
	}

	/**
	 * 
	 * @return
	 */
	public HashMap<String, Boolean> getPermissions() {
		return permissions;
	}

	/**
	 * 
	 * @param permissions
	 */
	public void setPermissions(HashMap<String, Boolean> permissions) {
		this.permissions = permissions;
	}

	/**
	 * 
	 * @return
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
	/**
	 * 
	 */
	public void salvarERecomecar() {
		try {
			permissions.clear();
			permissions.put("escolhendoAnimal", true);
			bo.save();
			bo.start();
		} catch (Exception exception) {
			manageThrowable(exception);
		}
	}
	
	/**
	 * 
	 */
	public void animalEscolhido() {
		try {
			permissions.clear();
			permissions.put("perguntandoSeAnimalEscolhidoTemHabilidade", true);
		} catch (Exception exception) {
			manageThrowable(exception);
		}
	}
	
	/**
	 * 
	 */
	public void animalPossuiAHabilidade() {
		try {
			permissions.clear();
			bo.moveToYesNode();
			if (bo.getCurrent().isLeaf()) {
				permissions.put("perguntandoSeEOAnimalEscolhido", true);
			} else {
				permissions.put("perguntandoSeAnimalEscolhidoTemHabilidade", true);
			}
		} catch (Exception exception) {
			manageThrowable(exception);
		}
	}
	
	/**
	 * 
	 */
	public void animalNaoPossuiAHabilidade() {
		try {
			permissions.clear();
			if (bo.getCurrent().isLeaf()) {
				permissions.put("perguntandoQualEOAnimal", true);
				bo.createAndMoveToNewNode();
			} else {
				bo.moveToNoNode();
				if (bo.getCurrent().isLeaf()) {
					permissions.put("perguntandoSeEOAnimalEscolhido", true);
				} else {
					permissions.put("perguntandoSeAnimalEscolhidoTemHabilidade", true);
				}
			}
		} catch (Exception exception) {
			manageThrowable(exception);
		}
	}
	
	/**
	 * 
	 */
	public void animalEscolhidoEncontrado() {
		try {
			permissions.clear();
			permissions.put("animalEscolhidoEncontrado", true);
		} catch (Exception exception) {
			manageThrowable(exception);
		}
	}
	
	/**
	 * 
	 */
	public void animalEscolhidoNaoEncontrado() {
		try {
			permissions.clear();
			if (bo.getCurrent().isLeaf()) {
				bo.createAndMoveToNewNode();
				permissions.put("perguntandoQualEOAnimal", true);
			} else {
				bo.moveToYesNode();
				permissions.put("perguntandoSeAnimalEscolhidoTemHabilidade", true);
			}
		} catch (Exception exception) {
			manageThrowable(exception);
		}
	}
	
	/**
	 * 
	 */
	public void adicionandoNovoAnimal() {
		try {
			permissions.clear();
			permissions.put("perguntandoAHabilidadeDoNovoAnimal", true);
		} catch (Exception exception) {
			manageThrowable(exception);
		}
	}
	
	/**
	 * Limpa o banco de dados da aplicação.
	 */
	public void apagarInformacoes() {
		try {
			bo.clear();
			permissions.clear();
			permissions.put("escolhendoAnimal", true);
			FacesMessager.addInfo("As informações previamente cadastradas foram removidas com sucesso.");
		} catch (Exception exception) {
			manageThrowable(exception);
		}
	}
	
	/**
	 * Retorna os dados guardados em formato json da aplicação para o estado original.
	 */
	public void retornarAoOriginal() {
		try {
			bo.backToDefaults();
			permissions.clear();
			permissions.put("escolhendoAnimal", true);
			FacesMessager.addInfo("As informações foram retornadas ao seu estado original.");
		} catch (Exception exception) {
			manageThrowable(exception);
		}
	}
	
	/**
	 * Este método tem o intuito de gerenciar todas as exceções do bean.
	 * Como esta foi uma implementação simples não cheguei ir além.
	 * Mas o intuito seria chamar um gerenciador global de exceções que
	 * 	captura e trata todas as exceções ou throwables do sistema, mostrando
	 * 	sempre uma mensagem tratada para o usuário.
	 * 
	 * @param throwable
	 */
	private void manageThrowable(Throwable throwable) {
		logger.error(throwable);
	}
}

src/main/webapp/xhtml/index.xhtml
<ui:composition
	template="/WEB-INF/private/xhtml/main/page.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
>
	<ui:define name="title">Jogo do Bicho</ui:define>
	<ui:define name="head_css_specific">
		<link
			href="#{request.contextPath}/css/index.css"
			rel="stylesheet"
			type="text/css"
		/>
	</ui:define>
	<ui:define name="content">
		<h:form
			id="menuForm"
		>
			<p:toolbar>
				<f:facet name="left">
<!-- 					<img -->
<!-- 						src="#{request.contextPath}/image/logo.svg" -->
<!-- 						alt="Jogo do Bicho" -->
<!-- 					/> -->
					<p:outputLabel value="Jogo do Bicho" />
				</f:facet>
				<f:facet name="right">
					<p:commandButton
						value="Início"
						onclick="window.location.reload();"
					/>
					<p:menuButton value="Opções">
						<p:menuitem
							value="Apagar Informações"
							actionListener="#{jogoDoBichoMB.apagarInformacoes()}"
							update=":growl, @(.game)"
						/>
						<p:menuitem
							value="Retornar ao Original"
							actionListener="#{jogoDoBichoMB.retornarAoOriginal()}"
							update=":growl, @(.game)"
						/>
					</p:menuButton>
				</f:facet>
			</p:toolbar>
		</h:form>
		<h:form
			id="gameForm"
			styleClass="game"
		>
			<p:outputPanel
				id="escolhendoAnimal"
				rendered="#{jogoDoBichoMB.permissions.escolhendoAnimal}"
			>
				<h2>Vamos começar! Primeiro pense em um animal.</h2>
				<h2>Quando você estiver pronto clique em continuar.</h2>
								
				<p:outputPanel styleClass="breath text-align-center">
					<p:commandButton
						value="Continuar"
						actionListener="#{jogoDoBichoMB.animalEscolhido()}"
						process="@this"
						update="@(.game)"
					/>
				</p:outputPanel>
			</p:outputPanel>
			
			<p:outputPanel
				id="perguntandoSeAnimalEscolhidoTemHabilidade"
				rendered="#{jogoDoBichoMB.permissions.perguntandoSeAnimalEscolhidoTemHabilidade}"
			>
				<h2>O animal que você pensou #{jogoDoBichoMB.current.question}?</h2>
				
				<p:outputPanel styleClass="breath text-align-center">
					<p:commandButton
						value="Sim"
						actionListener="#{jogoDoBichoMB.animalPossuiAHabilidade()}"
						process="@this"
						update="@(.game)"
					/>
					
					<p:commandButton
						value="Não"
						actionListener="#{jogoDoBichoMB.animalNaoPossuiAHabilidade()}"
						process="@this"
						update="@(.game)"
					/>
				</p:outputPanel>
			</p:outputPanel>
			
			<p:outputPanel
				id="perguntandoSeEOAnimalEscolhido"
				rendered="#{jogoDoBichoMB.permissions.perguntandoSeEOAnimalEscolhido}"
			>
				<h2>O animal que você pensou é o(a) #{jogoDoBichoMB.current.question}?</h2>
				
				<p:outputPanel styleClass="breath text-align-center">
					<p:commandButton
						value="Sim"
						actionListener="#{jogoDoBichoMB.animalEscolhidoEncontrado()}"
						process="@this"
						update="@(.game)"
					/>
					
					<p:commandButton
						value="Não"
						actionListener="#{jogoDoBichoMB.animalEscolhidoNaoEncontrado()}"
						process="@this"
						update="@(.game)"
					/>
				</p:outputPanel>
			</p:outputPanel>
		
			<p:outputPanel
				id="animalEscolhidoEncontrado"
				rendered="#{jogoDoBichoMB.permissions.animalEscolhidoEncontrado}"
			>
				<h2>Ahá! Acertei novamente!</h2>
				
				<p:outputPanel styleClass="breath text-align-center">
					<p:commandButton
						value="Jogar novamente"
						actionListener="#{jogoDoBichoMB.salvarERecomecar()}"
						process="@this"
						update="@(.game)"
					/>
				</p:outputPanel>
			</p:outputPanel>
			
			<p:outputPanel
				id="perguntandoQualEOAnimal"
				rendered="#{jogoDoBichoMB.permissions.perguntandoQualEOAnimal}"
			>
				<h2>Desisto...</h2>
				<h2>Qual foi o animal que você escolheu?...</h2>
				
				<p:inputText value="#{jogoDoBichoMB.current.yes.question}" />
				
				<p:outputPanel styleClass="breath text-align-center">
					<p:commandButton
						value="Continuar"
						actionListener="#{jogoDoBichoMB.adicionandoNovoAnimal()}"
						update="@(.game)"
						process=":gameForm:perguntandoQualEOAnimal"
					/>
				</p:outputPanel>
			</p:outputPanel>
			
			<p:outputPanel
				id="perguntandoAHabilidadeDoNovoAnimal"
				rendered="#{jogoDoBichoMB.permissions.perguntandoAHabilidadeDoNovoAnimal}"
			>
				<h2>Sobre esse(a) tal de #{jogoDoBichoMB.current.yes.question}...</h2>
				<h2>Preciso que você complete a seguinte frase...</h2>
				
				<p:outputPanel
					styleClass="text-align-center"
				>
					<h:outputText value="Um(a) #{jogoDoBichoMB.current.yes.question} " />
					<p:inputText value="#{jogoDoBichoMB.current.question}" style="width: 10em;" />
					<h:outputText value=" mas um(a) #{jogoDoBichoMB.current.no.question} não." />
				</p:outputPanel>
				
				<p:outputPanel styleClass="breath text-align-center">
					<p:commandButton
						value="Obrigado! Vamos tentar novamente!"
						actionListener="#{jogoDoBichoMB.salvarERecomecar()}"
						process=":gameForm:perguntandoAHabilidadeDoNovoAnimal"
						update="@(.game)"
					/>
				</p:outputPanel>
			</p:outputPanel>
		</h:form>
	</ui:define>
</ui:composition>